###  4.1 ndarray :다차원 배열 객체

In [1]:
import numpy as np

- __임의의 배열__ 생성

In [2]:
data = np.random.randn(2,3)

data

array([[ 1.12974348, -0.20755701,  0.69780977],
       [-1.2097363 ,  1.23555847,  1.23204503]])

- __산술연산__

In [3]:
data*10

array([[ 11.29743475,  -2.07557013,   6.97809775],
       [-12.09736303,  12.35558474,  12.32045032]])

In [4]:
data + data

array([[ 2.25948695, -0.41511403,  1.39561955],
       [-2.41947261,  2.47111695,  2.46409006]])

* __dtype__ 객체 : 자료형

In [6]:
data.dtype

dtype('float64')

* __shape__ 튜플: 차원의 크기

In [7]:
data.shape

(2, 3)

#### 4.1.1 ndarray 생성
- __array__ 함수

리스트를 넘겨받아 NumPy 배열 생성

In [8]:
data1 = [6, 7.5, 8, 0, 1]   # 리스트

arr1 = np.array(data1)      # NumPy array로 변환

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
arr1.dtype  # 자료형 추정

dtype('float64')

같은 길이를 가지는 리스트를 내포한 순차 데이터를 다차원 배열로 변환

In [9]:
data2 = [[1,2,3,4], [5,6,7,8]] # 리스트를 담고있는 리스트

arr2 = np.array(data2)         # 2차원 형태

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [12]:
arr2.dtype

dtype('int32')

- __zeros__ : 0이 들어있는 배열 생성
- __ones__ : 1이 들어있는 배열 생성
- __empty__ : 초기화되지 않은 배열 생성

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.empty((2,3,2))   # 0으로 초기화된 배열을 반환하는 것이 아니라, 초기화되지 않은 'garbage'값으로 채워진 배열 반환

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

* __arange__ : range 함수의 배열 ver.

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 4.1.2 ndarray의 dtype
* __dtype__ : ndarray가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보(=메타데이터)를 담고 있는 특수한 객체

In [18]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)


In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

* __astype__ : 배열의 dtype을 다른 형으로 변환(=캐스팅)

정수형을 부동소수점으로 변환

In [21]:
arr = np.array([1,2,3,4,5])

arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64)  # 변환: 정수형 → 부동소수점

float_arr.dtype

dtype('float64')

  
부동소수점수를 정수형으로 변환 : 소수점 아래 자리 버림

In [24]:
arr = np.array([6.3, -1.9, 0.9, 19.6, -6.1])

arr

array([ 6.3, -1.9,  0.9, 19.6, -6.1])

In [25]:
arr.astype(np.int32)  # 변환: 부동소수점 → 정수형

array([ 6, -1,  0, 19, -6])

  
숫자 형식의 문자열을 숫자형으로 변환

In [26]:
numeric_strings = np.array(['1.45', '-9.6', '96'])

numeric_strings.astype(float)

array([ 1.45, -9.6 , 96.  ])

다른 배열의 dtype 속성 이용

In [28]:
int_array = np.arange(10)

calibers = np.array([.22, .256, .357, .88, .64], dtype=np.float64)


In [29]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
int_array   # astype는 항상 새로운 배열을 생성(데이터를 복사)함을 확인

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 4.1.3 NumPy 배열의 산술 연산
- 벡터화 : for 문 작성 없이 데이터 일괄 처리  
같은 크기의 배열 간의 산술 연산 : 배열의 각 원소 단위로 적용

In [33]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr **0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

* 같은 크기의 배열 간 비교 연산은 boolian 배열을 반환

In [38]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

#### 4.1.4 색인과 슬라이싱 (기초)
- 1차원 배열

배열 조각에 스칼라값 대입하면 선택 영역 전체에 값이 전파 (broadcasting) 된다

In [40]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5:8]

array([5, 6, 7])

In [42]:
arr[5:8]=12  # 스칼라값 대입

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

변경된 데이터는 원본 배열에 반영된다! (데이터가 복사되는 것이 아닌, 원본 배열의 __뷰__)  
  
배열 복사를 하려면? → arr[5:8]__.copy()__ 

In [43]:
arr_slice = arr[5:8]

arr_slice

array([12, 12, 12])

In [44]:
arr_slice[1] =12345

arr    # arr_slice의 값을 변경하면 원래 배열인 arr 값도 바뀌는 것을 확인

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

- 2차원 배열

각 색인(index)에 해당하는 요소는 스칼라 값이 아닌 1차원 배열

In [45]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]

array([7, 8, 9])

개별 요소 접근하기

In [46]:
arr2d[2][0]

7

In [47]:
arr2d[2, 0]   # [row, column]

7

- 슬라이스로 선택하기

1차원

In [48]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [49]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

2차원

In [50]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr2d[:2]     # arr2d의 시작부터 두번째 row까지 선택

array([[1, 2, 3],
       [4, 5, 6]])

다차원 슬라이싱

In [54]:
arr2d[:2, 1:]   # 항상 같은 차원의 배열에 대한 뷰를 얻는다.

array([[2, 3],
       [5, 6]])

정수 index와 슬라이스를 함께 사용하면 한 차원 낮은 슬라이스를 얻을 수 있다

In [55]:
arr2d[1, :2]

array([4, 5])

In [56]:
arr2d[:2, 2]

array([3, 6])

#### 4.1.5 불리언값으로 선택하기

In [57]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7,4)

In [58]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [59]:
data

array([[-0.78433129, -0.39190894, -2.29889966,  1.44098483],
       [ 0.86880857, -0.77646572,  0.33283776, -0.69880658],
       [-1.15354096,  0.56487679, -2.42191106,  0.24741876],
       [ 0.10917529, -0.76684438, -0.70337497,  0.41277134],
       [-0.47911432,  1.43338418,  1.16815225, -0.35755917],
       [ 0.97407242,  0.55329152,  0.06954505, -0.42903   ],
       [ 0.2845341 ,  0.09440396, -1.53427709,  0.17793571]])

names의 각 이름이 data의 각 row에 대응한다고 가정

In [60]:
names == 'Bob'  # names 배열을 'Bob' 문자열과 비교 - 불리언 배열 반환

array([ True, False, False,  True, False, False, False])

In [62]:
# 위의 불리언 배열을 data의 색인으로 사용

data[names == 'Bob']  # 값이 True인 첫번째와 네번째 행만 선택

array([[-0.78433129, -0.39190894, -2.29889966,  1.44098483],
       [ 0.10917529, -0.76684438, -0.70337497,  0.41277134]])

불리언 배열 색인을 이용한 슬라이스 / 요소 선택

In [63]:
data[names == 'Bob', 2:]

array([[-2.29889966,  1.44098483],
       [-0.70337497,  0.41277134]])

- __~__ 연산자 : 일반적인 조건을 반대로 쓸 때 유용

In [64]:
cond = names == 'Bob'

data[~cond]  # 'Bob'이 아닌 요소들이 선택됨

array([[ 0.86880857, -0.77646572,  0.33283776, -0.69880658],
       [-1.15354096,  0.56487679, -2.42191106,  0.24741876],
       [-0.47911432,  1.43338418,  1.16815225, -0.35755917],
       [ 0.97407242,  0.55329152,  0.06954505, -0.42903   ],
       [ 0.2845341 ,  0.09440396, -1.53427709,  0.17793571]])

- __&__ (and) 연산자
- __|__ (or) 연산자

In [65]:
mask = (names == 'Bob') | (names == 'Will')

mask

array([ True, False,  True,  True,  True, False, False])

- 불리언 배열에 값 대입

In [67]:
data[data<0]=0  # data의 모든 음수값을 0으로

data

array([[0.        , 0.        , 0.        , 1.44098483],
       [0.86880857, 0.        , 0.33283776, 0.        ],
       [0.        , 0.56487679, 0.        , 0.24741876],
       [0.10917529, 0.        , 0.        , 0.41277134],
       [0.        , 1.43338418, 1.16815225, 0.        ],
       [0.97407242, 0.55329152, 0.06954505, 0.        ],
       [0.2845341 , 0.09440396, 0.        , 0.17793571]])

In [69]:
data[names != 'Joe'] = 7   # 조건에 해당하는 모든 row의 값 변경

data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.86880857, 0.        , 0.33283776, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.97407242, 0.55329152, 0.06954505, 0.        ],
       [0.2845341 , 0.09440396, 0.        , 0.17793571]])

#### 4.1.6 팬시 색인 Fancy Indexing
정수 배열을 사용한 색인  
슬라이싱과 달리 선택된 데이터를 새로운 배열로 복사

In [70]:
arr = np.empty((8,4))

for i in range(8):
    arr[i]=i

In [71]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

* 특정한 순서로 row 선택

In [72]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [73]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

* 다차원 색인 배열

In [74]:
arr = np.arange(32).reshape((8,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [75]:
arr[[1,5,7,2],[0,3,1,2]]  # (1,0) (5,3) (7,1) (2,2) 에 해당하는 원소 선택. 결과는 항상 1차원

array([ 4, 23, 29, 10])

각 row와 column에 대응하는 사각형 모양의 값 선택

In [76]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 4.1.7 배열 젙치와 축 바꾸기

- __T__ 속성

In [77]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

- 행렬의 내적 : __np.dot__

In [79]:
arr = np.random.randn(6,3)

arr

array([[ 0.6635282 ,  0.13978317,  1.52985608],
       [ 0.18152405, -1.26205398,  0.45068171],
       [-1.82505228, -0.44580774, -1.1955576 ],
       [-0.16633002,  0.17250497, -0.05794218],
       [-0.23052121, -0.23348681, -0.04775075],
       [-0.70318387,  0.89297599,  0.49199778]])

In [80]:
np.dot(arr.T, arr)

array([[4.37930974, 0.07448394, 2.95354753],
       [0.07448394, 2.69274429, 0.61854838],
       [2.95354753, 0.61854838, 4.22063085]])

- __transpose__ 메서드  
다차원 배열: 튜플로 축 번호를 받아서 치환

In [81]:
arr = np.arange(16).reshape((2,2,4))

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [82]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

* __swapaxes__ 메서드  
두 개의 축 번호를 받아서 배열을 뒤바꿈

In [83]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])