### 4.3 배열을 이용한 배열지향 프로그래밍

In [1]:
import numpy as np

#### 4.3.1 배열 연산으로 조건절 표현
* __np.where__ : x if 조건 else y
    * 새로운 배열 생성

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

# cond == True 이면 xarr 값, cond == False 이면 yarr 값
result = np.where(cond, xarr, yarr)

result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [3]:
# 스칼라값으로 바꾸기

arr = np.random.randn(4,4)

arr

array([[-0.68040372,  0.69091421, -1.44724523, -0.52091345],
       [-0.73454882, -0.43164766, -0.31716824, -1.91814043],
       [-1.30081201,  0.31597529,  1.58969683, -1.73384277],
       [-0.21952601, -0.16363342, -0.41369484, -0.69474198]])

In [4]:
arr>0

array([[False,  True, False, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [5]:
np.where(arr>0, 2, -2)  # True(양수)면 2, False(음수)면 -2 대입

array([[-2,  2, -2, -2],
       [-2, -2, -2, -2],
       [-2,  2,  2, -2],
       [-2, -2, -2, -2]])

In [6]:
# 스칼라와 배열의 조합

np.where(arr>0, 2, arr)  # 양수인 경우만 2 대입

array([[-0.68040372,  2.        , -1.44724523, -0.52091345],
       [-0.73454882, -0.43164766, -0.31716824, -1.91814043],
       [-1.30081201,  2.        ,  2.        , -1.73384277],
       [-0.21952601, -0.16363342, -0.41369484, -0.69474198]])

#### 4.3.2 수학 메서드, 통계 메서드
* __sum, mean, std__
    * axis=0 : 각 row에서 같은 위치의 값들끼리 계산 (열 별로 연산)
    * axis=1 : 각 column에서 같은 위치 값들끼리 계산 (행 별로 연산)

In [7]:
arr = np.random.randn(5,4)

arr

array([[-0.22759859,  0.2526947 ,  0.68358933,  0.01011575],
       [-1.16851689,  0.048542  ,  0.09702555, -0.17952791],
       [ 0.03120458, -2.19302612,  0.38666955,  1.40961994],
       [ 1.33085424,  1.04904965,  0.37514095,  0.44652219],
       [ 1.03846145, -0.61438832,  1.00667386,  1.20468231]])

mean()

In [8]:
arr.mean()

0.2493894104641626

In [9]:
np.mean(arr)

0.2493894104641626

In [10]:
arr.mean(axis=0)  # 모든 row에서 평균 구하기

array([ 0.20088096, -0.29142562,  0.50981985,  0.57828245])

sum()

In [11]:
arr.sum()

4.987788209283252

In [12]:
arr.sum(axis=1) # column의 합 구하기

array([ 0.71880118, -1.20247725, -0.36553205,  3.20156702,  2.63542931])

* __cumsum, cumprod__ : 중간 계산값을 담은 배열 반환  
  
cumsum() : 누적합을 같은 크기의 배열로 반환

In [13]:
arr = np.array([0,1,2,3,4,5,6,7])

arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

축 지정 : 부분적으로 계산, 낮은 차수의 슬라이스 반환

In [14]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [16]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

#### 4.3.3 불리언 배열을 위한 메서드
* __sum()__ : True 원소의 갯수 세기

In [17]:
arr = np.random.randn(100)

(arr>0).sum()

50

* __all()__ : 모든 원소가 True인지 검사
* __any()__ : True인 값이 있는지 검사

In [18]:
bools = np.array([False, True, False])

In [19]:
bools.all()

False

In [20]:
bools.any()

True

#### 4.3.4 정렬
* __sort( )__ : 정렬된 결과를 가진 복사본 반환

In [21]:
arr = np.random.randn(6)

arr

array([ 0.07310799,  0.5593915 , -0.7660165 ,  0.06646298, -0.06240008,
        2.16099338])

In [23]:
arr.sort()

arr

array([-0.7660165 , -0.06240008,  0.06646298,  0.07310799,  0.5593915 ,
        2.16099338])

다차원 배열 정렬 : 축의 값에 따라 1차원 부분 정렬

In [24]:
arr = np.random.randn(5,3)

arr

array([[ 0.33558502,  0.14230093,  0.78023626],
       [-0.4123943 , -1.05501744,  0.54215407],
       [ 1.21231171,  0.21351937, -0.11614604],
       [ 0.22445764,  0.75429767, -1.99627393],
       [-1.03995301, -1.8530786 , -0.87298909]])

In [26]:
arr.sort(1)

arr

array([[ 0.14230093,  0.33558502,  0.78023626],
       [-1.05501744, -0.4123943 ,  0.54215407],
       [-0.11614604,  0.21351937,  1.21231171],
       [-1.99627393,  0.22445764,  0.75429767],
       [-1.8530786 , -1.03995301, -0.87298909]])

In [28]:
arr.sort(0)

arr

array([[-1.99627393, -1.03995301, -0.87298909],
       [-1.8530786 , -0.4123943 ,  0.54215407],
       [-1.05501744,  0.21351937,  0.75429767],
       [-0.11614604,  0.22445764,  0.78023626],
       [ 0.14230093,  0.33558502,  1.21231171]])

배열의 분위수 구하기

In [29]:
large_arr = np.random.randn(1000)

large_arr.sort()

large_arr[int(0.05 * len(large_arr))]  # 5 % 분위수


-1.6349269782996179

#### 4.3.5 집합 관련 함수
* __np.unique( )__ : 배열 내 중복 원소 제거 & 남은 원소 정렬된 형태로 반환

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [31]:
ints = np.array([3,3,3,2,2,1,1,4,4])

np.unique(ints)

array([1, 2, 3, 4])

* __np.in1d__ : 2개의 배열을 인자로 받아서 첫 번째 배열의 원소가 두 번째 배열의 원소에 해당되는지 나타내는 불리언 배열 반환

In [32]:
values = np.array([6,0,0,3,2,5,6])

np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])