In [1]:
import numpy as np

### 4.5 선형대수
* __dot__ 함수 : 행렬 곱셈

In [2]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

y = np.array([[6.,23.],[-1,7],[8,9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [5]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

2차원 배열 * 1차원 배열 = 1차원 배열

In [7]:
np.dot(x, np.ones(3))

array([ 6., 15.])

* __@__ 연산자 : 행렬곱셈

In [8]:
x @ np.ones(3)

array([ 6., 15.])

* __numpy.linalg__ : 행렬의 분할, 역행렬, 행렬식 등등등

In [13]:
from numpy.linalg import inv, qr

X = np.random.rand(5,5)

mat = X.T.dot(X)


In [14]:
inv(mat)

array([[ 25.3162775 , -11.88377364,  38.16057719, -30.04612624,
        -28.06273202],
       [-11.88377364,   6.74151885, -19.69703026,  14.83824674,
         13.27574811],
       [ 38.16057719, -19.69703026,  69.70739885, -54.0020498 ,
        -43.19079683],
       [-30.04612624,  14.83824674, -54.0020498 ,  44.04749893,
         31.92147451],
       [-28.06273202,  13.27574811, -43.19079683,  31.92147451,
         34.20396962]])

In [15]:
q, r = qr(mat)

r

array([[-4.270361  , -3.08352808, -3.45256849, -3.94897389, -2.99256978],
       [ 0.        , -0.94089402, -0.20814921, -0.05107049,  0.1595875 ],
       [ 0.        ,  0.        , -0.51353738, -0.52990589, -0.15213919],
       [ 0.        ,  0.        ,  0.        , -0.08746078,  0.10231662],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.01411661]])

### 4.6 난수 생성
* numpy.random 모듈
  
normal : 표준정규분포로부터 표본 생성

In [17]:
samples = np.random.normal(size=(4,4))

samples

array([[-0.07783134, -1.35939035, -0.79219066,  1.46986029],
       [ 0.20077699,  0.39699302, -0.7694636 ,  0.76757994],
       [-0.23015556,  0.92322123, -1.53621506, -1.64941036],
       [-0.43429607,  0.45638338,  0.28232614,  0.67399106]])

RandomState : 다른 난수 생성기로부터 격리된 난수 생성기 만듦

In [18]:
rng = np.random.RandomState(1234)

rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])